name: Sync files to test.md

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ImageClassifierDoc/**'

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub GitPython # Add any other dependencies your script requires

      - name: Set Git Config
        run: |
          git config --local user.email "saifeemustafaq@gmail.com"
          git config --local user.name "saifeemustafaq"

      - name: Run Sync Script
        run: python .github/scripts/sync_script.py
        env:
          YOUR_GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
